name: Deploy Application

on:
  workflow_dispatch:
    inputs:
      home:
        description: "location"
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Push to Heroku
        run: git push -f https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/heroku.git origin/master:heroku
